# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: eperez96/ubuntu-custom-calc:v1.0


# Caracter | sirve para definir un multitask script
stages:
- stage: Build_and_Test
  jobs:
  - job: Build
    steps:
    - bash: echo Building...
    - bash: make
  - job: Test
    steps:
    - bash: echo Testing...
    - bash: sh test.sh
- stage: Build Docker Image
  jobs:
  - job: Docker_Login
    steps:
    - bash: docker login -u eperez96 --password 8e489e6f-5639-4ee1-9f3d-ebde39b7e100
  - job: Docker_Build
    steps:
    - bash: make
    - bash: sudo docker build -t eperez96/Calc_asm:v1.$(Build.BuildNumber) .
  - job: Docker_Push
    steps:
      - bash: sudo docker push eperez96/ubuntu-custom-calc:v1.$(Build.BuildNumber)

# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - bash: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeployJob
      